# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: 掘金
    url: https://juejin.im/user/59424035128fe1006a1c3747
  - name: 博客园
    url: https://www.cnblogs.com/DM428/
  - name: 新浪微博
    url: https://m.weibo.cn/profile/5198069647
  - name: GitHub
    url: https://github.com/zhongdeming428

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives
  - name: Comments
    slug: comments
    url: /comments
  - name: About
    slug: about
    url: /about

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/zhongdeming428
- slug: twitter
  url: https://twitter.com/kevinsfork
- slug: rss
	url: /atom.xml
